// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrbwxdsvaohsvvriozzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyYnd4ZHN2YW9oc3Z2cmlvenpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MDY0ODQsImV4cCI6MjA1MjI4MjQ4NH0.rg3qsdr_qPxYY_dznc_ph1UoX_eNvs9sL5E-JnGH3Lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);